package com.mpip.chatstation.Config;

public enum SystemMessagePacketType
{
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_NOT_CONFIRMED,
    SERVER_CLOSED,
    REQUEST_USER_DATA,
    CONFIRMATION_CODE_SUCCESS,
    CONFIRMATION_CODE_FAILED
}
